### ISSUE TITLE
Starting reading dust sensor on port /dev/ttyUSB0...

### ISSUE THREAD

**Issue by Bra1nsen** [MatejKovacic/SDS011-SDS018-and-SDS021-dust-sensors-reader#2]
first of all I changed:

sys.stdout = os.fdopen(sys.stdout.fileno(), 'w', "0") to

sys.stdout = os.fdopen(sys.stdout.fileno(), 'w')

to fix this error:

```
Traceback (most recent call last):
  File "dust-sensor-read.py", line 15, in <module>
    sys.stdout = os.fdopen(sys.stdout.fileno(), 'w', 0)
  File "/usr/lib/python3.7/os.py", line 1026, in fdopen
    return io.open(fd, *args, **kwargs)
ValueError: can't have unbuffered text I/O
```

now after: python dust-sensor-read.py
 i only get 
`Starting reading dust sensor on port /dev/ttyUSB0...`

any recommendation?

**Comment by MatejKovacic** [comment]
Very good. Thank you.
